name: Counter

on:
  schedule:
    - cron: '0/5 * * * *'

jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings with current time
        run: |
          now = $(date)
          echo 'Hello! The time is $now'
