name: Counter

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        default: 'Juan'
        type: string
  schedule:
    - cron: '*/5 * * * *'

jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings with current time
        run: echo "Hello, ${{ github.event.inputs.name }}! The time is $(date)"
