name: Counter

on:
  workflow_dispatch:

jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings with current time
        run: |
          now = $(date)
          echo 'Hello! The time is $now'
