name: Webhook workflow

on:
  repository_dispatch:
    types:
      - deploy
      - test

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo ${{ toJSON(github.event) }}'

  deploy:
    if: ${{ github.event.event_type == 'deploy' }}
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "I''m deploying..."'

  test:
    if: ${{ github.event.event_type == 'test' }}
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "I''m testing..."'
