name: Webhook workflow

on:
  repository_dispatch:
    types:
      - deploy
      - test

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Event type is: ${{ github.event.action }}"'

  deploy:
    if: ${{ github.event.action == 'deploy' }}
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "I''m deploying..."'

  test:
    if: ${{ github.event.action == 'test' }}
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "I''m testing..."'
